theme: jekyll-theme-minimal
title: Differentiable Agent-Based Models
description: Tutorial on differentiable ABMs at AAMAs 2024.
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: poole/lanyon #pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
