#theme: jekyll-theme-minimal
title: " "
#description: Tutorial on differentiable ABMs at AAMAs 2024.
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: riggraz/no-style-please #poole/hyde #pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
